[tool.black]
line-length = 100
skip_magic_trailing_comma = true

[tool.isort]
atomic = true
line_length = 100
profile = "black" 
skip_gitignore = true
known_first_party = ["pybliotecario"]
force_sort_within_sections = true
